version: '3.8'

services:
  personal-site:
    image: shotah/blodgett-site:latest
    container_name: personal-site
    environment:
      - VIRTUAL_HOST=$${LETSENCRYPT_HOSTNAME}
      - LETSENCRYPT_HOST=$${LETSENCRYPT_HOSTNAME}
      - LETSENCRYPT_EMAIL=$${LETSENCRYPT_EMAIL}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - VIRTUAL_PORT=3000
    networks:
      - my-network
    restart: always
    env_file:
      - .env

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy # Force the container name
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my-network
    depends_on:
      - personal-site
    restart: always
    env_file:
      - .env

  nginx-proxy-companion:
    image: nginxproxy/acme-companion
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - my-network
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=$${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
    env_file:
      - .env

networks:
  my-network:
